### ISSUE TITLE
Project upstreaming and permanance questions

### ISSUE THREAD

**Issue by quozl** [iqraceme/Primero1#1]
G'day,

I've seen some of your meetings on #sugar-meeting.

I see this repository is standalone and not based at sugarlabs organisation on GitHub, nor on the [sugarizer](https://github.com/llaske/sugarizer/network/members) repository maintained by Lionel.

I'd like you and your team to decide;
* whether the project should be in the sugarlabs organisation on GitHub,
* whether the project will be upstreaming useful changes up to Lionel's project.

Thanks!

**Comment by cemeiq** [comment]
Hi! We have decided that project be moved in the sugarlabs organization on Github

**Comment by quozl** [comment]
:grin:
